INSERT INTO USER (ID,USER_ID, PASSWORD, NAME, EMAIL) values (1,'kms2234','1234','sup2','kms2234@hanmail.net');

INSERT into QUESTION(ID,WRITER_ID, TITLE, CONTENTS, CREATE_DATE) values(1,1,'테스트1','테스트이다',CURRENT_TIMESTAMP());
INSERT into QUESTION(ID,WRITER_ID, TITLE, CONTENTS, CREATE_DATE) values(2,1,'테스트2','테스트이다',CURRENT_TIMESTAMP());